name: Cub3d CD

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten (emsdk)
        uses: mymindstorm/setup-emsdk@v14

      - name: 1. Compile MLX42 for Web
        run: |
          cd libs/MLX42
          mkdir -p build
          cd build
          emcmake cmake .. -DPLATFORM=Web
          emmake make

      - name: 2. Compile libft
        run: |
          cd libs/libft
          make CC=emcc AR=emar

      - name: 3. Compile Cub3D Sources to WebAssembly
        run: |
          PRELOAD_FLAGS=""
          if [ -d "maps" ]; then PRELOAD_FLAGS="$PRELOAD_FLAGS --preload-file maps@/maps"; fi
          if [ -d "textures" ]; then PRELOAD_FLAGS="$PRELOAD_FLAGS --preload-file textures@/textures"; fi
          
          mkdir -p out

          SRC_FILES=$(find src -name "*.c")

          emcc $SRC_FILES \
            libs/libft/libft.a libs/MLX42/build/libmlx42.a \
            -I./includes \
            -I./libs/MLX42/include \
            -I./libs/libft/includes \
            $PRELOAD_FLAGS \
            -O3 \
            -s USE_GLFW=3 \
            -s WASM=1 \
            -s ALLOW_MEMORY_GROWTH=1 \
            -s INITIAL_MEMORY=67108864 \
            -o out/index.html

      - name: 4. Inject Map Argument
        run: |
          JS_FILE="out/index.js"
          
          MAP_ARG="/maps/vine_maze.cub"
          
          echo "var Module = typeof Module !== 'undefined' ? Module : {};" > temp.js
          echo "Module.arguments = ['$MAP_ARG'];" >> temp.js
          cat "$JS_FILE" >> temp.js
          mv temp.js "$JS_FILE"

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages